[project]
name = 'Peer-to-Peer-Payment_Evolution'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Peer-to-Peer-Payment_Evolution]
path = 'contracts/Peer-to-Peer-Payment_Evolution.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
